# Site configuration
# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 
paginate_path: blog/page:num 
jekyll-mentions: https://twitter.com 
twitter:
  username: moreno_lab 
author: MorenoLab 
social: 
  name: Moreno Lab 
  links:  
    - https://x.com/moreno_lab
    - https://github.com/morenolab
    - https://www.linkedin.com/company/moreno-lab/about/

# 4. Jekyll settings
sass:
  style: compressed 
permalink: pretty  
excerpt_separator: 
timezone: America/Mexico_City # Updated to match lab location in Mexico City

# 5. Collections
collections:
  posts:
    title: Posts 
    output: true
    description: "My thoughts and ideas" 
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post 
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page 

# 7. Site settings
encoding: utf-8 
lang: en-GB 
title: "MorenoLab" 
logo: "/assets/logos/logo_moreno_home.png" 
css_inline: true 

# 8. Site favicons & manifest icons
favicons: 
  16: '/assets/logos/logo_moreno_small.png'
  32: '/assets/logos/logo_moreno_small.png'
  96: '/assets/logos/logo_moreno_small.png'
  120: '/assets/logos/logo_moreno_small.png'
  144: '/assets/logos/logo_moreno_small.png'
  180: '/assets/logos/logo_moreno_small.png'
  512: '/assets/logos/logo_moreno_small.png'
  1024: '/assets/logos/logo_moreno_small.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Team
  url: /team/
- title: Projects
  url: /projects/
- title: News
  url: /news/
- title: Publications
  url: /publications/
- title: Contact
  url: /contact/
- title: MXBiobank
  url: https://www.mxbiobank.org
- title: MexVar
  url: https://morenolab.shinyapps.io/mexvar/

social_links: 
  Twitter: https://x.com/moreno_lab
  GitHub: https://github.com/morenolab
  LinkedIn: https://www.linkedin.com/company/moreno-lab/about/

sharing_links: 
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
